From 974627cb79309a313d71f61e52061e3bfdda3ed1 Mon Sep 17 00:00:00 2001
From: Jack Olivieri <jolivieri@anaconda.com>
Date: Mon, 10 Feb 2025 16:03:00 +0100
Subject: [PATCH] fix import error exception

---
 tf_keras/distribute/multi_worker_testing_utils.py | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

diff --git a/tf_keras/distribute/multi_worker_testing_utils.py b/tf_keras/distribute/multi_worker_testing_utils.py
index a40220043..f5d10db6d 100644
--- a/tf_keras/distribute/multi_worker_testing_utils.py
+++ b/tf_keras/distribute/multi_worker_testing_utils.py
@@ -126,7 +126,7 @@ def pick_unused_port():
         while True:
             try:
                 port = portpicker.pick_unused_port()
-            except portpicker.NoFreePortFoundError:
+            except AttributeError:
                 raise unittest.SkipTest(
                     "Flakes in portpicker library do not represent "
                     "TensorFlow errors."
-- 
2.39.5 (Apple Git-154)

